/// <reference lib="webworker" />

type WorkerRequest = {
  id: string;
  payload: {
    asset: string;
    amount: string;
    decimals: number;
  };
};

type WorkerResponse = {
  id: string;
  result: {
    ok: boolean;
    proof?: string;
    notes: string[];
  };
};

const ctx: DedicatedWorkerGlobalScope = self as unknown as DedicatedWorkerGlobalScope;

ctx.onmessage = (event: MessageEvent<WorkerRequest>) => {
  const { id, payload } = event.data;
  const notes = [
    "Mock proof generated by worker.",
    `asset=${payload.asset}`,
    `amount=${payload.amount}`,
  ];

  const response: WorkerResponse = {
    id,
    result: {
      ok: true,
      proof: `mock-proof-${Date.now()}`,
      notes,
    },
  };

  ctx.postMessage(response);
};
